Repository ppy/osu-queue-score-statistics, pull requests merged in 2022-08, with the labels that each got.

#65 Fix `watch` command failing with empty `solo_scores_process_history` table
  osu.Server.Queues.ScorePump/Queue/WatchNewScores.cs
Labels: size/XS

#67 Don't increase user max combo on non-ranked beatmaps
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
Labels: size/M

#69 Fix `max_combo` overflowing on database reads
  osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStats.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
Labels: size/XS

#74 Remove `deleted_at` from `SoloScore` model
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
Labels: size/XS

#73 Change CI to use release branch for pushes
  .github/workflows/pack.yml
Labels: size/XS

#75 Backport: Add osu!lazer score `maximum_statistics` upgrade command
  osu.Server.Queues.ScorePump/AddMaximumStatisticsToLazerScores.cs
  osu.Server.Queues.ScorePump/Program.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs
Labels: size/L

#77 Add missing `LIMIT` to fetch query in migration command
  osu.Server.Queues.ScorePump/AddMaximumStatisticsToLazerScores.cs
Labels: size/XS
