Repository ppy/osu-queue-score-statistics, pull requests merged in 2022-07, with the labels that each got.

#39 Various improvements to high score importer
  osu.Server.Queues.ScorePump/ImportHighScores.cs
  osu.Server.Queues.ScorePump/Program.cs
  osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#43 Import highscore date into `score->data->ended_at`
  osu.Server.Queues.ScorePump/ImportHighScores.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
Labels: size/M

#48 Fix incorrect keys into osu_counts table
  osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs
Labels: size/XS

#50 Split PerformanceProcessor implementation to statistics processor classes
  osu.Server.Queues.ScorePump/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScorePump/Performance/PerformanceProcessor.cs
  osu.Server.Queues.ScorePump/Performance/Scores/UpdateAllScores.cs
  osu.Server.Queues.ScorePump/Performance/Scores/UpdateScoresFromList.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/DatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BuildStore.cs
Labels: size/XXL

#51 Use new score processing methods in ScorePerformanceProcessor
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/M

#52 Add user total performance processing
  osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Labels: size/M

#55 Filter `osu_builds` query to relevant builds
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Build.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BuildStore.cs
Labels: size/XS

#56 Fix incorrect database name in tables
  osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs
Labels: size/S

#58 Fix TD scores not being recalculated by the PP processor
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/XS

#59 Add environment variable to enable processing user totals
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/XS

#57 Update to use shared model class from `osu.Game`
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/DatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/HitStatisticsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#61 Update packages
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#60 Push scores to ES indexer queue after processing is complete
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Labels: size/M

#62 Mark passed scores as preserve
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Labels: size/XS

#64 👷 Add Docker builds
  .github/workflows/pack.yml
Labels: size/M
