Repository ppy/osu-queue-score-statistics, pull requests merged in 2022-11, with the labels that each got.

#101 Update dependencies
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#102 Fix missing beatmap ruleset
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/S

#103 Split tests out on a per-processor type basis
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/LegacyModsHelperTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
Labels: size/XXL

#104 Fix crash on looking up databased attributes when none are present
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/XS

#106 Update osu nuget packages
  osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#109 Bump `osu.Game` dependencies again to fix oversight in `1123` taiko dll
  osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#108 Change production check to be portable
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs
Labels: size/S

#105 Add unit testing
  .github/workflows/ci.yml
  osu.Server.Queues.ScorePump/.github/workflows/pack.yml
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/.github/workflows/pack.yml
Labels: size/L

#110 Add basic `docker-compose` setup
  .github/workflows/ci.yml
  docker-compose.yml
Labels: size/M

#111 Clean up `CancellationToken` handling
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
Labels: size/L
