Repository ppy/osu-queue-score-statistics, pull requests merged in 2022-12, with the labels that each got.

#113 Add ability to arbitrarily setup beatmaps and sets
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapSet.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/L

#112 Expose errors from queue processor during tests (and fix erroring tests)
  osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#115 Add basic environment setup documentation
  .github/workflows/ci.yml
  README.md
  docker-compose.yml
  osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/M

#107 Add medal processor
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings
  osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Medal.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/IMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
Labels: size/XL

#117 Add missing `ORDER BY` syntax to `solo_scores` pagination
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
  osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs
  osu.Server.Queues.ScorePump/Queue/WatchNewScores.cs
Labels: size/XS

#116 Refactor beatmap adding to remove implicit default
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/AddBeatmapTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
Labels: size/L

#120 Guard against imported legacy scores potentially being processed
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Labels: size/S

#121 Add support for realtime legacy score importing (and automatic indexing)
  osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ElasticQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Labels: size/L

#118 Target alternative pp column
  osu.Server.Queues.ScorePump/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStats.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#122 Calculate `rank_index` as part of performance total process
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/L

#123 Add ability to turn off medal awarding
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
Labels: size/XS

#124 Add local checkout scripts for `osu-queue-processor`
  UseLocalQueueProcessor.ps1
  UseLocalQueueProcessor.sh
Labels: size/M

#125 Publish messages about score processing completion to redis
  osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Messages/ScoreProcessed.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/M

#126 Fix max combo missed during solo-score import
  osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs
Labels: size/XS

#127 Disallow PP for non-default rate adjustments
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/S
