Repository ppy/osu-queue-score-statistics, pull requests merged in 2022-09, with the labels that each got.

#76 Make the highscore importer provide the `MaximumStatistics` dictionary
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
  osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#79 Import `has_replay` and `legacy_score_id` into solo scores
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#80 Import `has_replay` into column instead
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
Labels: size/S

#82 Centralise table names to allow for more easily adding a test prefix
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
  osu.Server.Queues.ScorePump/Queue/PumpAllScores.cs
  osu.Server.Queues.ScorePump/Queue/WatchNewScores.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/ProcessHistory.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreLegacyIDMap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScorePerformance.cs
Labels: size/S

#81 🎨 Use uppercase SCHEMA env var for consistency
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Labels: size/XS

#84 Add better error handling output
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
Labels: size/M

#85 Use `ulong` for highscore imports
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
  osu.Server.Queues.ScorePump/Queue/WatchNewScores.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/ScoreItem.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/M

#86 Add CI workflow
  .config/dotnet-tools.json
  .github/workflows/ci.yml
Labels: size/M

#87 Add command to upgrade scores
  osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs
  osu.Server.Queues.ScorePump/QueueCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#89 Add TouchDevice mod combination
  osu.Server.Queues.ScoreStatisticsProcessor/LegacyModsHelper.cs
Labels: size/XS

#90 Remove MaximumStatistics assert
  osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs
Labels: size/XS

#91 Cache all max combo lookups
  osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
Labels: size/S

#92 👷 Deploy to staging on every commit
  .github/workflows/pack.yml
Labels: size/S

#93 🔥 Remove unnecessary bloat in Docker image
  osu.Server.Queues.ScorePump/Dockerfile
  osu.Server.Queues.ScoreStatisticsProcessor/Dockerfile
Labels: size/XS
