Repository ppy/osu-queue-score-statistics, pull requests merged in 2023-09, with the labels that each got.

#152 Fix error code on unknown argument
  osu.Server.Queues.ScoreStatisticsProcessor/Program.cs
Labels: size/XS

#153 Fix new highscores not being imported
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Labels: size/S

#149 Add support for increasing rank counts
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/UserRankCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/L

#154 Add command to migrate playlist scores from `multiplayer_scores` to `solo_scores`
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratePlaylistScoresToSoloScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
Labels: size/L

#156 Don't run certain processors for failed scores
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/HitStatisticsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/IMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/L

#155 Read scoring attributes from the new table
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapScoringAttributes.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/M
