Repository ppy/osu-queue-score-statistics, pull requests merged in 2023-11, with the labels that each got.

#165 Pre-fetch beatmap to avoid querying multiple times across processors
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/M

#136 Add command to reprocess playlist total scores to *old* standardised scores
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/RecalculatePlaylistTotalScoresCommand.cs
Labels: size/L

#164 Limit play count increases to only increment below a certain rate limit
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Labels: size/M

#166 Add support for incrementing global and beatmap playcounts
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Labels: size/M

#167 Ensure `pp` is populated before attempting to import a legacy score
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Labels: size/S

#168 Update database connection retrieval to use new helper method (and remove `BaseCommand`)
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/BaseCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratePlaylistScoresToSoloScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/RecalculatePlaylistTotalScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromListCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromSqlCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateAllUserTotalsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ClearQueueCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpTestDataCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchQueueCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#169 Add ability to disable any processor when watching a queue
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchQueueCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/M

#171 Fix user level not being updated in database
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs
Labels: size/M

#172 Update packages
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#173 Always query maximum amount when not checking slave latency
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Labels: size/XS

#174 Reduce maximum number of scores per query
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Labels: size/XS
