Repository ppy/osu-queue-score-statistics, pull requests merged in 2023-08, with the labels that each got.

#135 Convert legacy total score to standardised when importing high scores
  osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScorePump/RecalculateScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/StreamedWorkingBeatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#137 Fix beatmap object counts data type
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
Labels: size/S

#138 Update all remaining commands to use `OnExecuteAsync` instead of `OnExecute`
  osu.Server.Queues.ScorePump/Queue/ClearQueueCommand.cs
  osu.Server.Queues.ScorePump/Queue/PumpAllScoresCommand.cs
  osu.Server.Queues.ScorePump/Queue/PumpTestDataCommand.cs
  osu.Server.Queues.ScorePump/Queue/WatchNewScoresCommand.cs
Labels: size/S

#139 Combine projects, tidy up namespaces, update README
  .github/workflows/pack.yml
  README.md
  osu.Server.Queues.ScorePump/Dockerfile
  osu.Server.Queues.ScorePump/Program.cs
  osu.Server.Queues.ScorePump/Queue/WatchNewScoresCommand.cs
  osu.Server.Queues.ScorePump/RecalculateScoresCommand.cs
  osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/LegacyModsHelperTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.sln
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/BaseCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresForUsersCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromListCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromSqlCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UpdateScoresCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UpdateUserTotalsCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateAllUserTotalsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateUserTotalsForUsersCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/PerformanceCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ClearQueueCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpTestDataCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/RunQueueCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DapperExtensions.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyModsHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyRulesetHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Messages/ScoreProcessed.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/ScoreItem.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Program.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/StreamedWorkingBeatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#142 Document environment variables and rename env var for consistency
  README.md
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
Labels: size/M

#144 Add command to clean up non-preserved scores
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Program.cs
Labels: size/M

#145 Add command to revoke preserved flag from scores which no longer require it
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
Labels: size/L

#148 Add ability to re-run score imports and update existing items
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Labels: size/L

#147 Add command to delete imported high scores
  osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Labels: size/L

#151 Replace all usage of `TABLE_NAME` constants with direct table names
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapDifficultyAttribute.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapSet.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Build.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/PerformanceBlacklistEntry.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/ProcessHistory.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreLegacyIDMap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScorePerformance.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BuildStore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/StreamedWorkingBeatmap.cs
Labels: size/L
