Repository ppy/osu-queue-score-statistics, pull requests merged in 2024-01, with the labels that each got.

#194 Verify command
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteImportedHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Labels: size/L

#196 Fix some entries not waiting for performance population before importing
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Labels: size/S

#197 Remove redundant `score.Passed` checks
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/RankedScoreProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
Labels: size/S

#198 Update to use new table structure
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/RankedScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/UserRankCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteImportedHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/PerformanceBlacklistEntry.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreData.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreLegacyIDMap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScorePerformance.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/XL

#199 Refactor to avoid fragmentation
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Labels: size/XL

#200 Do not count scores set on broken unranked beatmaps towards user total score
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/PlayValidityHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/L

#201 Fix some issues with watch mode
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Labels: size/XS

#202 Update verify scores command to handle total score and legacy total score
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
Labels: size/L

#204 Point user performance processor to update final pp value
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStats.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/S

#203 Use updated accuracy & grade definitions when importing stable scores
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/M

#207 Add datadog logging of time taken per-processor
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/M

#205 Optimise user PP total calculation
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/L

#206 Add command to watch non-high-scores
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Labels: size/L

#208 Don't throw on failure to convert scores
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchScoresCommand.cs
Labels: size/S
