Repository ppy/osu-queue-score-statistics, pull requests merged in 2024-10, with the labels that each got.

#283 Use static ruleset classes rather than constructing on each usage
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyRulesetHelper.cs
Labels: size/S

#282 Cache finalised attributes to avoid conversion overhead every usage
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/M

#281 Split latency checker out into a helper class
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/SlaveLatencyChecker.cs
Labels: size/M

#284 Score processing command updates for upcoming (and future PP deploys)
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresByUserCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UpdateScoresCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/L

#285 Add environment variable to allow disabling client build checks
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/XS

#286 Don't cache invalid/missing difficulty attributes
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StarRatingMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/L

#288 Add new process modes to score processing command
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
Labels: size/S

#290 Fix slow recent play lookup query by forcing index usage
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Labels: size/XS

#289 Unapply non-buffered performance optimisation
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
Labels: size/M

#291 Use manual connection pooling for score reprocessing
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
Labels: size/M

#262 Refactor `BeatmapStore` to use `MemoryCache`
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/L
