Repository ppy/osu-queue-score-statistics, pull requests merged in 2024-02, with the labels that each got.

#210 Make verify command faster by bypassing second-level data lookup
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Labels: size/L

#214 Order by `score_id` instead of `queue_id`
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Labels: size/XS

#215 Add a timeout condition to avoid score watchers getting stuck
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Labels: size/M

#217 Fix `BatchInserter` not showing correct process range due to no guaranteed ordering
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
Labels: size/XS

#219 Add verification step for confirming replay flag is correct
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Labels: size/S

#220 Change verify command to support batched writes
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Labels: size/L

#218 Use reintroduced `IMod.Ranked` property from game to determine eligibility of score for pp
  .config/dotnet-tools.json
  .github/workflows/ci.yml
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings
  osu.Server.Queues.ScoreStatisticsProcessor/Dockerfile
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#223 More correctly set ranked flag for imported non-high scores
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
Labels: size/XS

#224 Fix `BatchInserter` optimisation breaking insertion order requirements
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs
Labels: size/M

#225 Add command to verify presence of replays on S3
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyReplayExistsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#226 Update github actions to resolve deprecation warnings
  .github/workflows/ci.yml
  .github/workflows/pack.yml
Labels: size/S

#227 Stop marking scores as `ranked = 0` for pp only purposes
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/M
