Repository ppy/osu-queue-score-statistics, pull requests merged in 2024-03, with the labels that each got.

#229 Fix play count processor not incrementing pass count
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Labels: size/M

#195 Implement all non-Hush-Hush medals
  .editorconfig
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyReplayExistsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ElasticQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/MedalAwarderContext.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/HitStatisticsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/IMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/ModIntroductionMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StarRatingMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StatisticsMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/XXL

#231 Fix pack medal awarding failing for beatmap sets in more than one pack
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
Labels: size/XS

#232 Fix failed plays being included in pack medal query
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
Labels: size/M

#234 Do not grant challenge pack medals for scores that don't grant pp
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
Labels: size/L

#236 Delete score pins when cleaning up old user high scores during high score import
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Labels: size/S

#237 Add command for migration of `solo_scores` to `scores`
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratedSoloScoresToScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
Labels: size/L

#238 Update user highest rank & rolling rank history
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/L

#239 Add command to process total PP for users based on sql
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UpdateUserTotalsCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateUserTotalsFromSqlCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/M

#240 Fix possible overestimation of inserted row count in batch inserter
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
Labels: size/XS

#212 Backfill PP in `ScorePerformanceProcessor` to `osu_scores_high` on legacy scores
  README.md
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/S

#235 Implement rank milestone medals
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/RankMilestoneMedalAwarder.cs
Labels: size/L

#241 Fix failing test
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/XS

#243 Delete replays from S3 when cleaning up non-preserved scores
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyReplayExistsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/S3.cs
Labels: size/M

#242 Add processor for mania keymode user stats
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/ManiaKeyModeUserStatsProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/UserTotalPerformanceAggregateHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStatsManiaKeyCount.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/XL

#244 Check for multiplayer usage of score before marking it as non-preserved
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
Labels: size/S

#230 Prepare infrastructure for implementing hush-hush medals
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalAwarderTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/ModIntroductionMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/L

#247 Fix some test-specific issues
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalAwarderTest.cs
Labels: size/M
