Repository ppy/osu-queue-score-statistics, pull requests merged in 2024-05, with the labels that each got.

#265 Update packages
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/XS

#264 Decouple score processor from `SoloScoreInfo` model
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalAwarderTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/RankedScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresForUsersCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromSqlCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateAllUserTotalsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateUserTotalsForUsersCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateUserTotalsFromSqlCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/PlayValidityHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapSet.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/MedalAwarderContext.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStats.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/HitStatisticsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/LastPlayedDateProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/ModIntroductionMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StarRatingMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StatisticsMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/RankedScoreProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/XL

#254 Check ranked state when determining user best score in mark non-preserved scores command
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MarkNonPreservedScoresCommandTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
Labels: size/L

#270 Add partition cache for `user_rank_index` updates
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L

#271 Reduce verbosity of `verify-imported-scores` command
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Labels: size/S
