Repository ppy/osu-queue-score-statistics, pull requests merged in 2024-04, with the labels that each got.

#248 Add processor to update last played date in user stats table
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/LastPlayedDateProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/LastPlayedDateProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Labels: size/M

#251 Never include self when querying for current rank
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Labels: size/XS

#250 Add command to fix score ordering
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/ReindexBeatmapCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/ReorderIncorrectlyImportedTiedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
Labels: size/L

#255 👷 Trigger remote tag and build on private repo
  .github/workflows/pack.yml
Labels: size/S

#256 👷 Add pending approval Discord notification
  .github/workflows/pack.yml
Labels: size/M

#253 Add verify step to confirm correct `ranked` flag
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Labels: size/XS

#257 Upgrade game packages
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/ElasticQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/S

#258 Check ranked state when retrieving user best scores
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/ManiaKeyModeUserStatsProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/RankedScoreProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/UserRankCountProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs
Labels: size/M

#259 General code quality improvements
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalAwarderTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapSet.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/ModIntroductionMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StarRatingMedalAwarder.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Labels: size/L

#260 💚 Rename secret
  .github/workflows/pack.yml
Labels: size/XS

#261 💚 Set master as the target revision
  .github/workflows/pack.yml
Labels: size/XS

#263 Fix missing beatmap when running score PP processing via CLI
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/XS
