Repository ppy/osu-queue-score-statistics, pull requests merged in 2024-11, with the labels that each got.

#293 Batch attribute inserts into a single query
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
Labels: size/S

#292 Improve throughput of other commands using `ProcessPartitioned` by allowing transaction and connection sharing
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresByUserCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromListCommand.cs
Labels: size/M

#294 Fix console on non-user-interactive sessions
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
Labels: size/XS

#296 Use `GetConnectionAsync` wherever possible
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteImportedHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratePlaylistScoresToSoloScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratedSoloScoresToScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/PopulateTotalScoreWithoutModsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/RecalculatePlaylistTotalScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/ReindexBeatmapCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/ReorderIncorrectlyImportedTiedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyReplayExistsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresByUserCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromSqlCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateAllUserTotalsCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateUserTotalsFromSqlCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/M

#297 Fix various content type issues on LIO request helpers
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Labels: size/S

#298 Fix faulty production check in database test setup
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
Labels: size/XS

#299 Adjust LIO request helper further
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Labels: size/S

#300 Split domain to which LIO requests are directed to envvar
  README.md
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
Labels: size/S

#303 Enable user rank processor on legacy scores
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
Labels: size/XS

#302 Fix multiple issues related to mania key count stats population
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs
Labels: size/L

#304 Add command to fix non-matching rank counts
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyUserRankCounts.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
Labels: size/L

#305 Add command to reprocess score ranks
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyScoreRanksCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
  osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Labels: size/L
