Repository ppy/osu-queue-score-statistics, pull requests merged in 2025-01, with the labels that each got.

#311 Fix flagrantly incorrect query
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DailySproutTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs
Labels: size/S

#313 Enable pack medal awarder for legacy scores
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
Labels: size/M

#315 Stop marking preserve on new score arriving
  osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/S

#316 Bump NVika tool to 4.0.0
  .config/dotnet-tools.json
Labels: size/XS

#317 Add command to reprocess a single score
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ProcessScoreCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
  osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Labels: size/M

#318 Add medal awarding criteria for new medal
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
Labels: size/XS

#319 Ensure pp is saved back to model when calculated
  osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Labels: size/XS

#320 Add command to process all scores
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ProcessAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs
  osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Labels: size/M
